In [1]:
import pandas as pd

## Gathering Data

In [2]:
df = pd.read_excel('data_makanan_kemasan_raw.xlsx', header=1)

print(df.shape)
display(df.head())

(315, 9)

,food_name,food_category,shelf_life_unopened_days,shelf_life_opened_days,ideal_storage_temp,temp_coefficient,preservatives_level,packaging_type,ph_level
0,Kopi Instan,Beverage,693.0,27,25.2,0.031,3,Plastik,4.71
1,Yoghurt Plain,Dairy,19.0,3,4.2,0.144,2,NaN,3.78
2,Kecap Manis,Sauce,345.0,64 hari,24.5,0.095,4,Botol Kaca,4.62
3,Selai Kacang,sauce,394.0,93,24.8,0.081,4,Botol Kaca,5.90
4,Yoghurt Plain,Dairy,19.0,3,4.2,0.154,2,Plastik,3.74

Dataset dari data_makanan_kemasan memiliki 305 baris dan 9 kolom

## Assessing Data

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 315 entries, 0 to 314
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   food_name                 315 non-null    object
 1   food_category             290 non-null    object
 2   shelf_life_unopened_days  306 non-null    float64
 3   shelf_life_opened_days    307 non-null    object
 4   ideal_storage_temp        291 non-null    float64
 5   temp_coefficient          296 non-null    float64
 6   preservatives_level       315 non-null    int64
 7   packaging_type            289 non-null    object
 8   ph_level                  292 non-null    float64
dtypes: float64(4), int64(1), object(4)
memory usage: 22.3+ KB

- `shelf_life_opened_days` memiliki type data yang salah.

In [4]:
df['shelf_life_opened_days'].unique()

array(['27', '3', '64 hari', '93', '64', '0', '2', '5', '14', '51', '7',
       '1', '79', '4', '90', '26', '13', '86', '6', '28', '66', nan,
       '58 hari', '85', '12', '30', '16', '55', '102', '33', '68', '15',
       '34', '32', '31', '59', '6 hari', '7 hari', '58', '57', '60', '25',
       '53 hari', '28 hari', '62', '3 hari', '29', '78', '95', '65', '67',
       '82', '97', '99', '52', '88', '2 hari', '92', '101', '32 hari',
       '61', '5 hari', '1 hari'], dtype=object)

- Karena type nya object, sebelum mengubahnya menjadi int64 atau float 64, kita melakukan pengecekan apa apa saja isi dari `shelf_life_opened_days` sebelum mengubahnya.

In [5]:
df.describe(include="all")

,food_name,food_category,shelf_life_unopened_days,shelf_life_opened_days,ideal_storage_temp,temp_coefficient,preservatives_level,packaging_type,ph_level
count,315,290,306.000000,307,291.000000,296.000000,315.000000,289,292.000000
unique,46,24,NaN,62,NaN,NaN,NaN,18,NaN
top,Minuman Energi,Beverage,NaN,1,NaN,NaN,NaN,Plastik,NaN
freq,12,71,NaN,40,NaN,NaN,NaN,76,NaN
mean,NaN,NaN,448.261438,NaN,19.897251,0.432821,3.571429,NaN,5.305959
std,NaN,NaN,289.017074,NaN,14.071673,5.808241,1.336817,NaN,1.349899
min,NaN,NaN,-10.000000,NaN,3.500000,-0.500000,-1.000000,NaN,-2.000000
25%,NaN,NaN,254.000000,NaN,4.500000,0.056000,3.000000,NaN,4.260000
50%,NaN,NaN,369.500000,NaN,24.800000,0.078000,4.000000,NaN,5.675000
75%,NaN,NaN,699.500000,NaN,25.200000,0.103250,4.000000,NaN,6.282500
max,NaN,NaN,1200.000000,NaN,200.000000,99.900000,10.000000,NaN,7.300000

- Nilain max dari `temp_coefficient` adalah 99 derajat celcius, yang dimana nilai ini tidak masuk akal
- `preservaties_level` memiliki nilai negatif.
- `ph_level` memiliki nilia negatif.

In [6]:
df.isnull().sum()

food_name                    0
food_category               25
shelf_life_unopened_days     9
shelf_life_opened_days       8
ideal_storage_temp          24
temp_coefficient            19
preservatives_level          0
packaging_type              26
ph_level                    23
dtype: int64

- Terdapat nilia kosong di beberapa kolom.

In [7]:
df.duplicated().sum()

np.int64(13)

- Memiliki 13 data duplikat

In [20]:
print('Unique values and dtypes for shelf_life_unopened_days:')
print(df['shelf_life_unopened_days'].unique())
print(df['shelf_life_unopened_days'].dtype)

print('\nUnique values and dtypes for ideal_storage_temp:')
print(df['ideal_storage_temp'].unique())
print(df['ideal_storage_temp'].dtype)

print('\nUnique values and dtypes for temp_coefficient:')
print(df['temp_coefficient'].unique())
print(df['temp_coefficient'].dtype)

print('\nUnique values and dtypes for ph_level:')
print(df['ph_level'].unique())
print(df['ph_level'].dtype)

print("\nUnique values for food_categor':")
print(df['food_category'].unique())
print(df['food_category'].dtype)

print("\nUnique values for packaging_type:")
print(df['packaging_type'].unique())
print(df['packaging_type'].dtype)

print("\nUnique values for shelf_life_opened_days:")
print(df['shelf_life_opened_days'].unique())
print(df['shelf_life_opened_days'].dtype)

Unique values and dtypes for shelf_life_unopened_days:
[ 693.   19.  345.  394.  381.  352. 1036.   22.  191.  265.  778.  291.
  401.  358.   20. 1105.  360.  -10.   87.  190.  273.  387.  386.  169.
  193.  370.  377.  763.   31.  789.   90. 1051.  744.  388.   21.   27.
  372. 1147.  258.  334.  371.  254.  296.  751.  284.  696.  737.  174.
  185.  175.  736.  783.  739.   82.  176.   89.  333.  749.  331.  168.
  382.  281.  218.  177.  366.  181.  774.  392.  691.  761.  330. 1167.
   29.  380.  295.  247.  694.  750.  775.  799.  336.   94.  356.  183.
  349.  712. 1066.  373.  171.  796.  773.  706.  369.  390.  782. 1174.
  226.  346.  364.  679.  755.  672.  338.  283.  267.  379.  374.  725.
 1093.  718.  700.   86.  692.  400.  362.  243.  344.  791.  363.  690.
  367.  353.  180.  659.  663. 1158.  801.   84.  784.  186.  285.  715.
   97.  375.  688.  184.  376.  701.  350. 1057.  277. 1121.  341.  389.
  689.  222.  260.  249.  741.  745.  671.  673.  727.  288.  723.   32.
   96.  759. 1200.  698.  399.  343. 1197. 1096.  722.  757.  340.  772.
  282.   -5.  357.  678.  670. 1144.  383.  248.  721.  195.  246.  230.
  287.  703. 1010.  798.  391.  328.  359. 1047.  792.  355.  278.  196.
 1025. 1134.  664.  658.  777.  683.  337.  263.  687.]
float64

Unique values and dtypes for ideal_storage_temp:
[ 25.2   4.2  24.5  24.8  25.1  25.4   4.1   9.7  24.7   4.3  25.    4.
   3.6  25.3   9.6  24.6   3.8   4.5  24.9  25.5   3.7  10.    4.4   3.9
   9.9   9.8   3.5 200.    9.5]
float64

Unique values and dtypes for temp_coefficient:
[ 3.10e-02  1.44e-01  9.50e-02  8.10e-02  1.54e-01  7.20e-02  7.80e-02
  5.30e-02  1.43e-01  1.14e-01  1.09e-01  9.10e-02  5.10e-02  1.22e-01
  6.10e-02  1.47e-01  4.20e-02  8.70e-02  5.80e-02  1.13e-01  7.90e-02
  6.00e-02  6.70e-02  9.80e-02  6.40e-02  3.80e-02  7.70e-02  5.60e-02
  3.70e-02  6.30e-02  1.56e-01  1.58e-01  8.60e-02  5.20e-02  1.24e-01
  1.19e-01  1.04e-01  9.30e-02  1.02e-01  1.23e-01  2.10e-02  1.21e-01
  8.00e-02  1.17e-01  7.10e-02  5.00e+00  3.20e-02  8.40e-02  5.70e-02
  1.08e-01  6.90e-02  4.30e-02  9.40e-02  9.60e-02  5.00e-02  1.20e-01
  1.29e-01  6.20e-02  4.50e-02  3.50e-02  1.06e-01  8.90e-02  8.50e-02
  1.28e-01  4.60e-02  1.01e-01  1.46e-01  8.30e-02  7.50e-02  9.20e-02
  4.40e-02  6.50e-02  4.90e-02  6.60e-02  1.15e-01  1.05e-01  9.00e-02
  1.10e-01  3.40e-02  1.11e-01  9.90e-02  1.25e-01  9.99e+01  3.90e-02
  3.30e-02  7.60e-02  1.03e-01  4.10e-02  1.26e-01  1.12e-01  5.40e-02
  1.27e-01  4.00e-02  2.50e-02  5.90e-02  8.80e-02  1.42e-01  7.00e-02
  4.70e-02  1.52e-01 -5.00e-01  1.18e-01  1.49e-01  2.90e-02  5.50e-02
  7.40e-02  6.80e-02  1.07e-01]
float64

Unique values and dtypes for ph_level:
[4.71  3.78  4.62  5.9   3.74  6.13  5.675 5.92  4.26  3.62  4.28  4.75
 5.83  6.59  3.65  6.47  4.3   5.87  4.67  4.57  6.96  6.25  3.72  5.09
 3.69  5.53  6.68  3.64  4.23  6.62  6.07  5.23  3.7   4.42  5.41  6.04
 4.89  6.8   3.54  3.73  6.66  4.13  6.5   4.76  6.09  6.65  6.15  5.95
 3.57  5.89  6.37  4.88  6.11  4.46  6.67  5.75  7.15  4.11  3.98  6.17
 3.95  6.69  3.9   5.42  6.73  6.43  6.29  6.57  4.05  5.47  4.99  3.99
 6.61  7.07  5.24  3.83  6.72  6.32  5.94  6.54  7.03  4.22  0.    3.71
 7.11  6.71  3.75  6.19  3.48  5.82  5.96  5.6   6.58  3.56  4.68  4.73
 5.78  6.53  4.12  5.76  5.55  5.01  3.66  3.79  5.11  3.92  3.97  5.05
 5.67  6.52  4.01  5.22  5.31  3.61  6.76  3.8   4.29  5.57  6.91  5.27
 4.36  6.39  3.84  3.77  6.41  6.14  4.47  6.23  5.54  7.12  5.46  4.51
 6.88  7.25  7.08  5.99  4.24  7.06  6.12  4.34  6.49  3.4   6.94  4.14
 3.86  4.07  6.28  4.52  5.58  6.92  7.09  4.06  4.87  6.21  5.28  6.74
 7.1   4.37  5.45  6.38  6.02  5.51  4.53  6.34  6.45  3.89  7.21  5.4
 3.94  6.2   5.43  4.38  5.69  7.18  3.28  5.98  6.56  4.    4.27  3.82
 7.3   7.02  6.22  4.21  5.77  6.3   4.03  5.68  6.86  6.16  6.98  4.45 ]
float64

Unique values for food_categor':
['minuman' 'produk susu' 'saus' 'kaleng' 'unknown' 'camilan']
object

Unique values for packaging_type:
['plastik' 'unknown' 'botol kaca' 'kaleng' 'karton']
object

Unique values for shelf_life_opened_days:
['27' '3' '64 hari' '93' '64' '0' '2' '5' '14' '51' '7' '1' '79' '4' '90'
 '26' '13' '86' '6' '28' '66' 'Unknown' '58 hari' '85' '12' '30' '16' '55'
 '102' '33' '68' '15' '34' '32' '31' '59' '6 hari' '7 hari' '58' '57' '60'
 '25' '53 hari' '28 hari' '62' '3 hari' '29' '78' '95' '65' '67' '82' '97'
 '99' '52' '88' '2 hari' '92' '101' '32 hari' '61' '5 hari' '1 hari']
object

## Cleaning Data

In [9]:
df.drop_duplicates(inplace=True)

duplicates_after_removal = df.duplicated().sum()
print(f"Jumlah baris duplikat setelah penghapusan: {duplicates_after_removal}")

Jumlah baris duplikat setelah penghapusan: 0

In [10]:
columns_to_fill = ['shelf_life_unopened_days', 'ideal_storage_temp', 'temp_coefficient', 'ph_level']

for col in columns_to_fill:
    median_value = df[col].median()
    df[col] = df[col].fillna(median_value)

print("Missing values after median imputation:")
print(df[columns_to_fill].isnull().sum())

Missing values after median imputation:
shelf_life_unopened_days    0
ideal_storage_temp          0
temp_coefficient            0
ph_level                    0
dtype: int64

In [11]:
df['food_category'] = df['food_category'].fillna('Unknown')
df['packaging_type'] = df['packaging_type'].fillna('Unknown')
df['shelf_life_opened_days'] = df['shelf_life_opened_days'].fillna('Unknown')

print("Missing values after imputation for categorical columns:")
print(df[['food_category', 'shelf_life_opened_days', 'packaging_type']].isnull().sum())

Missing values after imputation for categorical columns:
food_category             0
shelf_life_opened_days    0
packaging_type            0
dtype: int64

In [12]:
df['food_category'] = df['food_category'].astype(str).str.lower().str.strip()
print("Unique values for 'food_category' after normalization:")
print(df['food_category'].unique())

Unique values for 'food_category' after normalization:
['beverage' 'dairy' 'sauce' 'caned' 'canned' 'unknown' 'snaks' 'snack'
 'daory' 'beverag' 'dairi' 'sauced' 'minuman' 'kaleng']

In [13]:
category_mapping = {
    'caned': 'kaleng',
    'snaks': 'camilan',
    'snack': 'camilan',
    'daory': 'produk susu',
    'beverag': 'minuman',
    'dairi': 'produk susu',
    'dairy': 'produk susu',
    'sauced': 'saus',
    'sauce': 'saus',
    'beverage': 'minuman',
    'canned': 'kaleng'
}
df['food_category'] = df['food_category'].replace(category_mapping)

print("Unique values for 'food_category' after correcting inconsistencies:")
print(df['food_category'].unique())

Unique values for 'food_category' after correcting inconsistencies:
['minuman' 'produk susu' 'saus' 'kaleng' 'unknown' 'camilan']

In [14]:
df['packaging_type'] = df['packaging_type'].astype(str).str.lower().str.strip()
print("Unique values for 'packaging_type' after normalization:")
print(df['packaging_type'].unique())

Unique values for 'packaging_type' after normalization:
['plastik' 'unknown' 'botol kaca' 'kaleng' 'karton' 'tin' 'plastic'
 'glass bottle' 'botol']

In [15]:
packaging_mapping = {
    'plastic': 'plastik',
    'glass bottle': 'botol kaca',
    'botol': 'botol kaca',
    'tin': 'kaleng'
}
df['packaging_type'] = df['packaging_type'].replace(packaging_mapping)

print("Unique values for 'packaging_type' after correcting inconsistencies:")
print(df['packaging_type'].unique())

Unique values for 'packaging_type' after correcting inconsistencies:
['plastik' 'unknown' 'botol kaca' 'kaleng' 'karton']

In [18]:
median_preservatives_level = df[df['preservatives_level'] >= 0]['preservatives_level'].median()
df.loc[df['preservatives_level'] < 0, 'preservatives_level'] = median_preservatives_level

print(f"Median for non-negative 'preservatives_level': {median_preservatives_level}")
print("Negative values in 'preservatives_level' after correction:")
print(df[df['preservatives_level'] < 0]['preservatives_level'].count())

Median for non-negative 'preservatives_level': 4.0
Negative values in 'preservatives_level' after correction:
0

In [19]:
median_ph_level = df[df['ph_level'] >= 0]['ph_level'].median()
df.loc[df['ph_level'] < 0, 'ph_level'] = median_ph_level

print(f"Median for non-negative 'ph_level': {median_ph_level}")
print("Negative values in 'ph_level' after correction:")
print(df[df['ph_level'] < 0]['ph_level'].count())

Median for non-negative 'ph_level': 5.675
Negative values in 'ph_level' after correction:
0

In [21]:
cleaned_shelf_life = df['shelf_life_opened_days'].copy()
cleaned_shelf_life = cleaned_shelf_life.astype(str).str.replace(' hari', '', regex=False).str.replace('hari', '', regex=False)
cleaned_shelf_life = cleaned_shelf_life.replace('Unknown', pd.NA)
df['shelf_life_opened_days'] = pd.to_numeric(cleaned_shelf_life, errors='coerce')

print("First 5 rows of df['shelf_life_opened_days'] after cleaning:")
display(df[['food_name', 'shelf_life_opened_days']].head())

First 5 rows of df['shelf_life_opened_days'] after cleaning:

           food_name  shelf_life_opened_days
0        Kopi Instan                    27.0
1    Yoghurt Plain                       3.0
2        Kecap Manis                    64.0
3       Selai Kacang                    93.0
4      Yoghurt Plain                     3.0

In [22]:
median_shelf_life_opened_days = df[df['shelf_life_opened_days'] >= 0]['shelf_life_opened_days'].median()
df.loc[df['shelf_life_opened_days'] < 0, 'shelf_life_opened_days'] = median_shelf_life_opened_days

print(f"Median for non-negative 'shelf_life_opened_days': {median_shelf_life_opened_days}")
print("Negative values in 'shelf_life_opened_days' after correction:")
print(df[df['shelf_life_opened_days'] < 0]['shelf_life_opened_days'].count())

Median for non-negative 'shelf_life_opened_days': 4.0
Negative values in 'shelf_life_opened_days' after correction:
0

In [36]:
df.nlargest(3, 'temp_coefficient')

,food_name,food_category,shelf_life_unopened_days,shelf_life_opened_days,ideal_storage_temp,temp_coefficient,preservatives_level,packaging_type,ph_level
160,Yoghurt Strawberry,produk susu,27.0,3.0,4.4,99.900,2,plastik,4.36
54,Susu UHT Full Cream,produk susu,291.0,7.0,4.0,5.000,3,karton,6.65
38,Yoghurt Strawberry,unknown,27.0,3.0,24.8,0.158,10,plastik,4.42

In [39]:
df.loc[df['temp_coefficient'] == df['temp_coefficient'].max(), 'temp_coefficient'] = 5
df.nlargest(3, 'temp_coefficient')

,food_name,food_category,shelf_life_unopened_days,shelf_life_opened_days,ideal_storage_temp,temp_coefficient,preservatives_level,packaging_type,ph_level
54,Susu UHT Full Cream,produk susu,291.0,7.0,4.0,5.000,3,karton,6.65
160,Yoghurt Strawberry,produk susu,27.0,3.0,4.4,5.000,2,plastik,4.36
38,Yoghurt Strawberry,unknown,27.0,3.0,24.8,0.158,10,plastik,4.42

## Pengecekan ulang setelah cleaning

In [23]:
print("DataFrame Info after cleaning:")
df.info()
print("\nFirst 5 rows of the cleaned DataFrame:")
display(df.head())

DataFrame Info after cleaning:
<class 'pandas.core.frame.DataFrame'>
Index: 302 entries, 0 to 314
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   food_name                 302 non-null    object
 1   food_category             302 non-null    object
 2   shelf_life_unopened_days  302 non-null    float64
 3   shelf_life_opened_days    294 non-null    float64
 4   ideal_storage_temp        302 non-null    float64
 5   temp_coefficient          302 non-null    float64
 6   preservatives_level       302 non-null    int64
 7   packaging_type            302 non-null    object
 8   ph_level                  302 non-null    float64
dtypes: float64(5), int64(1), object(3)
memory usage: 23.6+ KB

First 5 rows of the cleaned DataFrame:

,food_name,food_category,shelf_life_unopened_days,shelf_life_opened_days,ideal_storage_temp,temp_coefficient,preservatives_level,packaging_type,ph_level
0,Kopi Instan,minuman,693.0,27.0,25.2,0.031,3,plastik,4.71
1,Yoghurt Plain,produk susu,19.0,3.0,4.2,0.144,2,unknown,3.78
2,Kecap Manis,saus,345.0,64.0,24.5,0.095,4,botol kaca,4.62
3,Selai Kacang,saus,394.0,93.0,24.8,0.081,4,botol kaca,5.90
4,Yoghurt Plain,produk susu,19.0,3.0,4.2,0.154,2,plastik,3.74

In [24]:
df.describe(include="all")

,food_name,food_category,shelf_life_unopened_days,shelf_life_opened_days,ideal_storage_temp,temp_coefficient,preservatives_level,packaging_type,ph_level
count,302,302,302.000000,294.000000,302.000000,302.000000,302.000000,302,302.000000
unique,46,6,NaN,NaN,NaN,NaN,NaN,5,NaN
top,Kopi Instan,minuman,NaN,NaN,NaN,NaN,NaN,plastik,NaN
freq,10,73,NaN,NaN,NaN,NaN,NaN,80,NaN
mean,NaN,NaN,446.082781,18.431973,20.209934,0.426056,3.589404,NaN,5.381689
std,NaN,NaN,284.398082,26.529920,13.780919,5.750252,1.240360,NaN,1.163544
min,NaN,NaN,-10.000000,0.000000,3.500000,-0.500000,0.000000,NaN,0.000000
25%,NaN,NaN,255.000000,2.000000,9.725000,0.057250,3.000000,NaN,4.292500
50%,NaN,NaN,370.000000,4.000000,24.800000,0.079000,4.000000,NaN,5.675000
75%,NaN,NaN,695.500000,27.000000,25.100000,0.100500,4.000000,NaN,6.245000
max,NaN,NaN,1200.000000,102.000000,200.000000,99.900000,10.000000,NaN,7.300000

In [25]:
print("Descriptive statistics after correcting negative values:")
display(df[['shelf_life_unopened_days', 'preservatives_level', 'ph_level']].describe())

Descriptive statistics after correcting negative values:

       shelf_life_unopened_days  preservatives_level    ph_level
count                302.000000           302.000000  302.000000
mean                 446.082781             3.589404    5.381689
std                  284.398082             1.240360    1.163544
min                  -10.000000             0.000000    0.000000
25%                  255.000000             3.000000    4.292500
50%                  370.000000             4.000000    5.675000
75%                  695.500000             4.000000    6.245000
max                 1200.000000            10.000000    7.300000

In [26]:
print("Data type for 'shelf_life_opened_days' after cleaning:")
print(df['shelf_life_opened_days'].dtype)

print("\nDescriptive statistics for 'shelf_life_opened_days' after cleaning:")
display(df['shelf_life_opened_days'].describe())

Data type for 'shelf_life_opened_days' after cleaning:
float64

Descriptive statistics for 'shelf_life_opened_days' after cleaning:

count    294.000000
mean      18.431973
std       26.529920
min        0.000000
25%        2.000000
50%        4.000000
75%       27.000000
max      102.000000
Name: shelf_life_opened_days, dtype: float64

In [27]:
df.describe(include='all')

,food_name,food_category,shelf_life_unopened_days,shelf_life_opened_days,ideal_storage_temp,temp_coefficient,preservatives_level,packaging_type,ph_level
count,302,302,302.000000,294.000000,302.000000,302.000000,302.000000,302,302.000000
unique,46,6,NaN,NaN,NaN,NaN,NaN,5,NaN
top,Kopi Instan,minuman,NaN,NaN,NaN,NaN,NaN,plastik,NaN
freq,10,73,NaN,NaN,NaN,NaN,NaN,80,NaN
mean,NaN,NaN,446.082781,18.431973,20.209934,0.426056,3.589404,NaN,5.381689
std,NaN,NaN,284.398082,26.529920,13.780919,5.750252,1.240360,NaN,1.163544
min,NaN,NaN,-10.000000,0.000000,3.500000,-0.500000,0.000000,NaN,0.000000
25%,NaN,NaN,255.000000,2.000000,9.725000,0.057250,3.000000,NaN,4.292500
50%,NaN,NaN,370.000000,4.000000,24.800000,0.079000,4.000000,NaN,5.675000
75%,NaN,NaN,695.500000,27.000000,25.100000,0.100500,4.000000,NaN,6.245000
max,NaN,NaN,1200.000000,102.000000,200.000000,99.900000,10.000000,NaN,7.300000

In [35]:
df.nlargest(10, 'temp_coefficient')

,food_name,food_category,shelf_life_unopened_days,shelf_life_opened_days,ideal_storage_temp,temp_coefficient,preservatives_level,packaging_type,ph_level
160,Yoghurt Strawberry,produk susu,27.0,3.0,4.4,99.900,2,plastik,4.36
54,Susu UHT Full Cream,produk susu,291.0,7.0,4.0,5.000,3,karton,6.65
38,Yoghurt Strawberry,unknown,27.0,3.0,24.8,0.158,10,plastik,4.42
37,Yoghurt Plain,produk susu,21.0,3.0,4.1,0.156,2,plastik,3.70
89,Yoghurt Strawberry,produk susu,29.0,3.0,3.8,0.156,2,plastik,4.26
4,Yoghurt Plain,produk susu,19.0,3.0,4.2,0.154,2,plastik,3.74
48,Yoghurt Plain,produk susu,20.0,4.0,4.1,0.154,2,plastik,4.13
242,Yoghurt Plain,produk susu,20.0,4.0,3.8,0.154,2,plastik,3.86
252,Yoghurt Strawberry,produk susu,32.0,2.0,3.6,0.152,2,plastik,3.94
278,Yoghurt Plain,produk susu,20.0,4.0,3.6,0.149,2,plastik,4.27

In [28]:
df.to_csv('dataset_makanan_kemasan_clean.csv', index=False)